export const KEYS = {
    getMe: 'get-me',
    profile: 'profile',
    employees: 'employees-list',
    topUsers: 'topUsers',
    kpd: 'kpd',
    incidents: 'incidents',
    incsByPeriod: 'incsByPeriod',
    incsByType: 'incsByType',
    statusComps: 'statusComps',
    organizationReports: 'organizationReports',
    activity: 'activity',
    keylogger: 'keylogger',
    buffer: 'buffer',
    screenshot: 'screenshot',
    alerts: 'alerts',
    accountList: 'accountList',
    computers: 'computers',
}