export const URLS = {
    login: 'central/auth/login',
    signUp: 'auth/sinup',
    profile: 'api/account/profile',
    employees: 'api/main/employees',
    topUsers: 'api/main/dashboard/topUsers',
    kpd: '/api/main/dashboard/kpd',
    incidents: '/api/main/dashboard/incident',
    incsByPeriod: '/api/main/dashboard/incsByPeriod',
    incsByType: '/api/main/dashboard/incsByType',
    statusComps: '/api/main/dashboard/statusComps',
    organizationReports: '/api/reports/incident/organization',
    activity: 'api/main/activity',
    keylogger: 'api/main/keylgrlist',
    buffer: 'api/main/clbrdlist',
    screenshot: '/api/main/scrshtlist',
    alerts: '/api/main/alerts',
    accountList: 'api/account/list',
    computers: 'api/main/computers',
    allIncidents: 'api/main/events/allincidents',
    visitList: '/api/main/visitlist',
    groups: 'api/main/policies/groups',
}