export const URLS = {
    login: 'api/central/auth/login',
    profile: 'api/central/profile',
    employees: 'api/central/employees/list',
    employee: 'api/central/employees',
    topUsers: 'api/main/dashboard/topUsers',
    kpd: '/api/main/dashboard/kpd',
    incidents: '/api/central/incidents/list',
    incsByPeriod: '/api/main/dashboard/incsByPeriod',
    incsByType: '/api/main/dashboard/incsByType',
    statusComps: '/api/main/dashboard/statusComps',
    organizationReports: '/api/reports/incident/organization',
    activity: 'api/central/employees/activity',
    keylogger: 'api/central/employees/keylogger',
    buffer: 'api/central/employees/clipboards',
    screenshot: '/api/central/employees/screenshot',
    alerts: '/api/main/alerts',
    accountList: 'api/account/list',
    computers: 'api/central/computers/list',
    allIncidents: 'api/main/events/allincidents',
    visitList: '/api/central/employees/web-visits',
    groups: 'api/central/groups',
    translations: 'api/central/language',
    webSniffs: '/api/central/employees/web-sniffs',
    webSearch: '/api/central/employees/web-search',
    documents: '/api/central/documents',
}